spring:
  application:
    name: oj-codesandbox
  config:
    activate:
      on-profile:
        - prod
server:
  port: 8088

sandbox:
  safety:
    blackWordList: ["File", "exec", "Runtime","write","read"]